### ISSUE TITLE
Missing fields 

### ISSUE THREAD

**Issue by david-morris** [insidewhy/wildcard-mock-link#126]
I've noticed that despite regenerating intermediate code, the selection set of a fragment (when printing the link object) was missing one of the fields from the document object that the query mock referred to. However, no errors were printed to either console.

So, I'm reporting the instability and incorrectness of the selection set generation, as well as silencing that error.

This was an optional field, but defining it as `null` on all items where it was missing did not change this behavior.

I'm probably not going to be able to reliably reproduce this bug.

This might be a caching issue. I could not change the order of the selection set when modifying the gql fragment.

I also tried to take things out of the relevant fragment to reset whatever cache got stuck.  It didn't work; nothing changed when I removed fields.

I've tried version 2.0.2 and 2.0.3.

**Comment by insidewhy** [comment]
Thanks for the report. Could you give me a small reproducion a some rough code sample?

**Comment by insidewhy** [comment]
Thanks for letting me know
