### ISSUE TITLE
Apollo Client V3 Support

### ISSUE THREAD

**Issue by realDT** [insidewhy/wildcard-mock-link#59]
Hi,
Do you have any plan to support Apollo Client V3 any time soon? 
Meantime, if you could provide any workaround would be greatly appreciated.

**Comment by realDT** [comment]
I forked the code and was able create a simple polyfill to make this work by changing all the imports from apollo V3

**Comment by insidewhy** [comment]
Cool, PR is welcome

**Comment by insidewhy** [comment]
@realDT Just to be sure, you only needed to change imports to support apollo v3?

**Comment by insidewhy** [comment]
@realDT Added support for v3 now in https://github.com/insidewhy/wildcard-mock-link/pull/61 will merge it once I get a review or two.

**Comment by insidewhy** [comment]
2.0.0 release candidates have been available for a while, released 2.0.0 today.
