### ISSUE TITLE
Provide option to disable missing mock warning.

### ISSUE THREAD

**Issue by martdavidson** [insidewhy/wildcard-mock-link#87]
We write a lot of large integration tests. Sometimes components will fire off queries that we don't care about for the test case.

MockedProvider ignores these by default, whereas this library is producing a console warning for every useQuery that doesn't have a matching mock.

I'd love an option in the WildcardMockLinkOptions to disable the console.warn in:

```
 const errorString = `No mocks matched ${op.operationName}: ${print(
          op.query,
        )}, variables: ${JSON.stringify(op.variables)}`
        console.warn(errorString)
```

Probably useful to make it so that the error _is_ shown in the case where you provided a mock for a given query / mutation, but provide the wrong variables. I think MockedProvider is also already handling that correctly.

Anyway, just an idea!

**Comment by insidewhy** [comment]
@martdavidson Both mocked providers will return an error to the hook when the mock is missing, if your code is fine dealing with that then it's cool. We added the warning specifically so we could diagnose issues where we were ignoring the warning but wanted to still be able to diagnose it. I can see why it might be annoying if you don't care, so I can add the option :) Or you can open a PR with that code also if you want it done urgently? It should be an easy change. I assume you're using the 2.0 release candidate? I'm promoting that to `2.0.0` very soon.

**Comment by martdavidson** [comment]
I am using 2.0.0-rc.6!

No urgency at all! If I get to it first, I'll submit a PR. Thanks for the response!
